### ISSUE TITLE
Remove obsolete and unused npm package

### ISSUE THREAD

**Issue by euberdeveloper** [eagletrt/eagletrt-telemetria-postprocessing#4]
Unused package: https://www.npmjs.com/package/eagletrt-telemetria-validator

Either remove (npm unpublish) or deprecate (`npm deprecate eagletrt-telemetria-validator "Deprecated in favour of @eagletrt/telemetria-postprocessing"`)

**Comment by nicolatoscan** [comment]
Package unpublished
